### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by insolor** [rdbende/flake8-tkinter#2]
flake8-tkinter v0.1.2, Python 3.8

During check of the following code, it throws an exception:
```python
import tkinter as tk

root = tk.Tk()


def func():
    a.b.c


bar=tk.Button(root, text="some text", command=func)
bar.pack(side=tk.TOP, fill=tk.X)

root.mainloop()
```
Error:
```
❯ flake8 bug.py
Traceback (most recent call last):
  File "/home/insolor/.local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/main/application.py", line 348, in _run
    self.run_checks()
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/main/application.py", line 262, in run_checks
    self.file_checker_manager.run()
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/checker.py", line 325, in run
    self.run_serial()
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/checker.py", line 309, in run_serial
    checker.run_checks()
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8/checker.py", line 496, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8_tkinter.py", line 172, in run
    visitor.visit(self.tree)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8_tkinter.py", line 148, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 381, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/insolor/.local/lib/python3.8/site-packages/flake8_tkinter.py", line 151, in visit_Attribute
    if node.value.id == data_dict.get("tkinter_imported_as") and node.attr in {
AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by rdbende** [comment]
Thanks for reporting this! I got this fixed, though I'm sure, it's still full of bugs
